# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-12-14 07:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='staff',
            options={},
        ),
        migrations.AddField(
            model_name='staff',
            name='password',
            field=models.CharField(default='123456', max_length=100),
        ),
    ]
