# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-12-15 09:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_auto_20171214_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='magazines',
            name='comment',
            field=models.TextField(blank=True, default='', max_length=200),
        ),
    ]
