# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-12-21 07:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_auto_20171221_1544'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='price_count',
            field=models.FloatField(default=0),
        ),
    ]
