# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-12-21 07:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_staff_price_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='price_count',
        ),
    ]
